### ISSUE TITLE
🧮 Core Team Only All Contributors Bot Add Contributors Here 🧮 

### ISSUE THREAD

**Issue by jbampton** [OmegaMath/omega#6]
https://allcontributors.org/

https://allcontributors.org/docs/en/emoji-key

**Comment by jbampton** [comment]
@all-contributors please add @jbampton for projectManagement

**Comment by jbampton** [comment]
@all-contributors please add @summerhill5 for doc

**Comment by jbampton** [comment]
@all-contributors please add @ Idaaraica for doc

**Comment by jbampton** [comment]
@all-contributors please add @Idaaraica for doc

**Comment by jbampton** [comment]
@all-contributors please add @basalumutgazi  for doc

**Comment by jbampton** [comment]
@all-contributors please add @all-contributors for doc

**Comment by displexic** [comment]
@all-contributors please add @shannon-nz for doc
